name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install -D
      - name: Build files
        run: yarn run build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: dist
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [build]
    steps:
      - name: Download all the dist
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: dist
      - name: Publication files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: releases
